name: Continuous Integration

on: [push, pull_request]
jobs:
  test:
    if: "!startsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{matrix.os.fullName}}
    strategy:
      matrix: 
        os: 
          - { prettyName: 'Linux', fullName: 'ubuntu-latest'}
        python-version: ['3.9', '3.10']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask/requirements.txt
      - name: Run tests
        working-directory: flask/tests
        run: python test.py
      - name: Run coverage
        working-directory: flask/tests
        run: python run_coverage.py headless